### ISSUE TITLE
Is there a better way to "ban" unwanted types, like DateTime?

### ISSUE THREAD

**Issue by lucax88x** [NeVeSpl/NetArchTest.eNhancedEdition#5]
This is something I came up in 5 minutes.

Still not perfect because I can still "create the class" with datetime and not use them.. but ok!

I could achieve the same result using [rosyln analyzers](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md)

```csharp
    [Fact]
    public void Test1()
    {
        var r = Types
            .InCurrentDomain()
            .That()
            .ResideInNamespaceContaining("Template.")
            .And()
            .MeetCustomRule(
                r1 => r1.Fields
                    .Any(f => f.FieldType.Name == nameof(DateTime))
            )
            .Should()
            .NotHaveDependencyOnAll()
            // .NotBeUsedByAny()
            .GetResult();

        r.IsSuccessful
            .Should()
            .BeTrue();
    }

```

**Comment by NeVeSpl** [comment]
Every rule is divided into two parts, before and after  `Should`:
- before `Should` - you select types for testing
- after `Should`-  you define constraints which given type should pass or not
 
so, an idiomatic way to write this rule would be:
```csharp
 var r = Types
     .InCurrentDomain()
     .That()
     .ResideInNamespaceContaining("Template.")                           
     .ShouldNot()
     .MeetCustomRule(
         r1 => r1.Fields
             .Any(f => f.FieldType.Name == nameof(DateTime))
     )
     .GetResult();
```

but I am not sure if this is what you are asking for.

**Comment by lucax88x** [comment]
What I'm asking is, if you wanted to prohibit the DateTime (or anything else) usage in the solution, how would you achieve that?

**Comment by NeVeSpl** [comment]
As you pointed out at the beginning, there are two ways, using Roslyn analyzers or through unit tests, both methods are valid, but they work on different levels.
